services:
  - type: web
    name: mini-google-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn search_api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: ASTRA_DB_API_ENDPOINT
        sync: false
      - key: ASTRA_DB_APPLICATION_TOKEN
        sync: false
      - key: ASTRA_DB_NAMESPACE
        value: default_keyspace
      - key: ASTRA_DB_COLLECTION
        value: pages
